version = 1

test_patterns = ["*/src/test/**"]

exclude_patterns = [
    "**/resources/**",
    "**/webapp/**"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"
